### ISSUE TITLE
Slider in right hand side or both left and right hand side.

### ISSUE THREAD

**Issue by fajarmf** [wnielson/sencha-SlideNavigation#1]
Hi,

First of all, I think this is a great code! It works well to show menu slider on the left hand side.
However, for my project, I need to have right hand side menu slider too, or even sometimes both left and right hand side.

So what I did was to modify createNavigationList, and moveContainer functions. I also created separate store for left and right list items. Thanks to your code, it all works, the lists can be shown in both left and/or right hand side. But I have this problem that the string in the right hand side list, is not shown ( empty string ).

Could you please help me to figure out what's happening?

I can attach my changes if you need me to.

thanks,
fajarmf

**Comment by fajarmf** [comment]
apparently I forgot to specify template for right hand side list. sorry about that. I have spent hours figuring out this.

Closing the issue now.

**Comment by ghost** [comment]
@fajarmf would you please tell me more about the changes you have made? I'm trying to get this working without success. Thanks in advance.
