### ISSUE TITLE
could not get the reference of list items in the controller

### ISSUE THREAD

**Issue by basureshkumar** [wnielson/sencha-SlideNavigation#14]
hi ,

First of all a big thanks for you great effort which helped a lot .

I have a small question
/\* In my Main.js inside view folder_/
  items: [{
            title: 'Item 1',
            group: 'Group 1',
            id:'item1'
            /_*
             \*  Here's an example of how we can add a button into
             \*  particular location.  In this case, it'll be added into the
             \*  item's toolbar.
             */
            slideButton: {
                selector: 'toolbar'
            },
            items: [{
                xtype: 'toolbar',
                title: 'Item 1',

```
            docked: 'top'
        },{
            xtype: 'panel',
            html: '<img src="resources/images/guide.jpg" width="100%" />'
        }]
    },{
        title: 'Item 2',
        id:'item2' 
        group: 'Group 1',
        /**
         *  Here's an example of how an item can simply execute a
         *  function, rather than display a new component.
         */
        handler: function() {
            Ext.Msg.alert('Item 2', 'You clicked Item 2.');
        }
    },
```

In the above code, i had defined 'id' for each element, in my controller when i refer this by id, i could not fetch the refered item

say in my controller

 /_left hand side navigation_/
            slideNav: 'slidenavigationview',
            item1:'#item1',

item1 is coming as undefined. Any idea about it ?

Actually i need to change the css of some items based  on some synchronization,

Thanks in advance!
Regards,
Bala

**Comment by wnielson** [comment]
This is most likely happening because the items are not actually created until they are accessed for the first time (then they are cached).  Take a look at the included controller example for an idea of how to do what you want.
