### ISSUE TITLE
work with container

### ISSUE THREAD

**Issue by koolll** [wnielson/sencha-SlideNavigation#15]
Hi, I am new for sencha touch.I love ur project so much. Btw I got a very noob question. Can I apply container to navigation panel?Which mean when I expand the navigation panel ,then it show a simple container , but not  list. Seem like the navigation panel only work for  a list. In addition , is it possible to dynamic load content within the navigation panel ? 

Hope you understand my question. Sorry for my noob question. Thanks

**Comment by wnielson** [comment]
Thanks!  Unfortunately achieving what you want isn't possible without modifying the code.  That said, I don't think it'd be too difficult to do.  You should start by taking a look at the `createNavigationList` method.  There are only a few other spots in the code where a list is expected, so you'll need to change those as well.  Good luck!
