### ISSUE TITLE
Push view and pop view

### ISSUE THREAD

**Issue by Syhoman** [wnielson/sencha-SlideNavigation#17]
Hi, when I was exploring the flexibility of the features, I encountered some issue.
As I know "sencha-SlideNavigation" extends "container", is it possible to push new view like sencha navigation view?
This means when a new view is pushed, "Back" button can be shown on the right hand side of tool bar.

http://docs.sencha.com/touch/2-0/#!/guide/navigation_view
view.push({
    title: 'New views title',
    html: 'Some content'
});

I am testing for a long time, but no luck to have a satisfactory result.

**Comment by wnielson** [comment]
There is no `push` or `pop` functions like on a `navigationview` component.  You can, however, use the `add` and `remove` methods on the `container` of the slide nav.  For example, if your slide navigation view is called `slidenav`, you can add and remove items from the container manually via calls to `slidenav.container.add` and `container.remove`.

Alternatively, you could add and remove items from the slide navigation view's internal `store` which is used to display the list and create the items.

**Comment by hessius** [comment]
I'm struggling with a similar problem. My default view is a list, when I want to use onitemdisclosure to show detailed info I was using .push but transitioned to setActiveItem instead (as I thought this would be compatible with SlideNavigation). It was working in a navigation view but since adding SlideNavigation it has not.
This was my code

``` javascript
Ext.getCmp('mainpanel').setActiveItem({
                                                 xtype: 'labdetail',
                                                 title: 'Detaljinformation',
                                                 data: record.getData()
                                                 });
```

After reading this thread I've also tried            

``` javascript
Ext.getCmp('mainpanel').add({
```

and 

``` javascript
Ext.getCmp('mainpanel').container.add({
```

(Note: When using the last method the view shows flipping for half a second before disappearing)

**Comment by hessius** [comment]
Oh NVM solved it by using

``` javascript
Ext.Viewport.animateActiveItem({
            xtype: 'labdetail',
            title: 'Detaljinformation',
            data: record.getData()
            },{
            type: 'slide', 
            direction: 'left'
            });
```

**Comment by hessius** [comment]
Oh sorry for the amount of comments here. Did solve the navigating to the detailed view. Applying the reverse method on a backbutton does not work though.
Targeting the main view (my slidenavigationview) does nothing, targeting the listview (which is just an item in the list of the slidenavigationview) removes the slidenavigationfunction... Does anyone know how to make the manual back button work in this case?

**Comment by wnielson** [comment]
I use this component with `Ext.navigation.View` components all the time, but it does take a little more effort to get it working properly.  The way I typically use it, the `slidebutton` is only visible when at the root component inside the navigation view.  If you listen to the `push` and `back` events on the `Ext.navigation.View`, you can then select the `slidebutton` and hide/show it as necessary.  For example (untested), here are example listeners:

``` javascript
back: function(nav) {
    if (nav.getInnerItems().length == 2) {
        bar = nav.getNavigationBar();
        bar.down('button[name="slidebutton"]').show({
            type: 'fade',
            out: false,
            duration: bar.getAnimation().duration
        });
    }
},
push: function(nav) {
    var bar = nav.getNavigationBar();
    bar.down('button[name="slidebutton"]').hide({
        type: 'fade',
        out: true,
        duration: bar.getAnimation().duration
    });
}
```

**Comment by hessius** [comment]
Thanks, I'll definately borrow that when I actually get pushing views working.
Do you have any code examples of working navigationviews?

Right now I tried making a new navigation view ("LabContainer") which is the default item of the mainview (which is my slidenavigationview). This navigation view is displaying my list.
When using Ext.getCmp('labcontainer').push() or this.getContainer().push() the detail page seems to get painted but never displayed (I get a console message from my painted listener on the details page, but my console message that should fire after the push function has completed is never fired).

Is this even the right approach? Am I missing a step, is there any tricks as how to configure the views?

**Comment by wnielson** [comment]
[This](https://github.com/wnielson/sencha-SlideViewExample) uses the newer (and more incomplete) Ext.ux.slide.View component, but the navigationview stuff should be pretty similar.

**Comment by hessius** [comment]
Thanks! Using the code in that example I got it working!
