### ISSUE TITLE
deploying locally I get a "Cannot call method 'substring' of undefined" error

### ISSUE THREAD

**Issue by pherris** [wnielson/sencha-SlideNavigation#18]
just deploying locally on windows, apache and using Chrome to view I get the above error. problem seems to originate from List.js

onItemAdd: function(item) {
        var me = this,
            config = item.config;

```
    if (config.scrollDock) {
        if (config.scrollDock == 'bottom') {
            me.scrollDockItems.bottom.push(item);
        } else {
            me.scrollDockItems.top.push(item);
        }
        item.addCls(Ext.baseCSSPrefix + 'list-scrolldock-hidden');
        if (me.container) {
            me.container.add(item);
        }
    } else {
        me.callParent(arguments); //<-- here
    }
},
```

**Comment by pherris** [comment]
ok, so I have to build the sample app to get it working _sheepish grin_. I'm new to the sdk. Trying this from the directory containing the app.js file 

$ sencha -sdk /cygdrive/c/tools/sencha-touch-2.1.0-commercial/ app build -e testing

 and getting this error:

Sencha Cmd v3.0.0.250
[ERR]           Please ensure this command was executed from a valid application
 directory
[ERR]           Unable to locate 'app.dir' config property from sencha.cfg

**Comment by pherris** [comment]
I think I'm missing something. I'm getting stuck on this command:

---

To build the example you need to put Sencha Touch into a folder named sdk.  Then run::

```
./sdk/commands/sencha app build -e testing
```

## This will produce the example app in the `build/testing` directory.

The sencha touch 2.1 release does not have a directory called commands in it. There is a cmd dir with a sencha.cmd in it. Am I on the right path?

**Comment by wnielson** [comment]
Sorry, the build directions are out of date.  I'll post the updated instructions shortly.

**Comment by pherris** [comment]
Thanks, part of the problem was my confusion between the Cfg tools and the old Sencha Tools. Following the updated instructions it works fine with one exception, I had to match the case of my directory to my requires statement:

requires = [
        'Ext.ux.slidenavigation.View',
    ]

instead of Ext.ux.SlideNavigation.

Thx.

**Comment by pherris** [comment]
wow, never mind - must have been me that capped the S and N. sorry - this is working great!

**Comment by wnielson** [comment]
Great, glad its working!

**Comment by eddiesigner** [comment]
Great job! But... How I can use the setActiveItem method from a button to change views?

My code:

xtype: 'button',
handler: function () {
    console.log(menuContainer.getActiveItem()); // Works fine
    menuContainer.setActiveItem(4); // Not working
}

Thx!

**Comment by eddiesigner** [comment]
never mind, I solved it :)

**Comment by Martin1982** [comment]
@eddiesigner for the sake of completeness, how did you solve it?

**Comment by eddiesigner** [comment]
With this line: 

menuContainer.list.select(4);

**Comment by lbernau** [comment]
"deploying locally I get a "Cannot call method 'substring' of undefined" error"

How did you fix this?
If I create a build version everything works fine, but just opening the folder throws this error.

**Comment by pherris** [comment]
Sorry, I don't recall... are you seeing it in the same location? When I redeployed the example it did start working out of the box, but I was in the middle of a hackathon and as soon as I passed this point I moved onto the next thing. Maybe if you provide additional context I can help you?

**Comment by wnielson** [comment]
Update and try again.

**Comment by lbernau** [comment]
Works fine. Ty.
