### ISSUE TITLE
Info FYI Ext.create, Ext.add in launch()

### ISSUE THREAD

**Issue by msimonc** [wnielson/sencha-SlideNavigation#19]
Hi,

Did you know that your project runs fine without calling Ext.Viewport.add as in:

Replace:
Ext.Viewport.add(Ext.create('SlideNavigationExample.view.Main'));

With:
Ext.create('SlideNavigationExample.view.Main').

Thanks

**Comment by wnielson** [comment]
Thanks for the tip.
