### ISSUE TITLE
slideButton on navigationBar

### ISSUE THREAD

**Issue by Tarang** [wnielson/sencha-SlideNavigation#26]
I have a navigation view with a navigationBar, how would I add the slideButton to it?

I've tried all sorts with the selector but i'm, not certain they're compatible. Is it possible to add the slidebutton onto the navigationview's toolbar (navigationBar)?

**Comment by ElMassimo** [comment]
Just use the following configuration in the sliding menu, and slideButton:true in the menu item that contains your navigation view.

``` javascript
        slideButtonDefaults: {
            selector: 'titlebar',
```

**Comment by Tarang** [comment]
Wow that was quick

I tried it but the button wont appear, heres the code i'm using:

``` javascript
slideButtonDefaults: {
            selector: 'titlebar',
}
...
    xtype : 'navigationview',
    id: 'homenav',
    title: 'Home',
    iconCls: 'home',
    slideButton:true,
    navigationBar: {
        //slideButton:true, //also tried this
        items: [ 
            { xtype:'button',text:'Next',ui:'forward',align:'right',id:'nextbutton',hidden:true}
         ]  
    }...
```

**Comment by Tarang** [comment]
if the above way can't work is there a way I can add

``` javascript
{ xtype: 'button' }
```

And attach a listener to it manually to slide the menu? Is this the toggleContainer method? But how would I call it? If i use this.toggleContainer it won't work

**Comment by ElMassimo** [comment]
Maybe you are misplacing the navigationview in the items configuration

``` javascript
config: {
    slideButtonDefaults: {
        selector: 'titlebar',
        ...
    },

    items: [
        {
            title: 'Home',
            slideButton:true,

            items:[
                {
                    xtype : 'navigationview',
                    ...
                }
            ]
        },
        ...
    ]
}
```

**Comment by Tarang** [comment]
Yes that works!! Fantastic!
