### ISSUE TITLE
Access an item on the navigation menu with js

### ISSUE THREAD

**Issue by Tarang** [wnielson/sencha-SlideNavigation#27]
Is there a way to acces these and hide these? Is there a way to access the items using an id or some other way with 

I see a way in the docs to use list, but im not sure how to use it entirely

``` javascript
Ext.getCmp(..)
```

**Comment by wnielson** [comment]
Yup.  The list shows whatever is in the store, so if you don't want to show a certain item, you need to filter the store.

```
var snv   = Ext.ComponentQuery.query('slidenavigationview')[0],
    store = snv.list.getStore();

store.filterBy(function(record, id) {
  // Put your filter logic here.  Example:
  return (id != 2);
});

```

**Comment by Tarang** [comment]
Is it possible to do something like Ext.getCmp('theitemid').hide();? the id fields dont seem to do anything with the items in a slidenav

**Comment by wnielson** [comment]
You can hide items in a list, but it won't give you the results you are looking for.  In my previous example, the "id" is not the component id, but rather the id of the component in the store that is bound to the list.  You can also filter items in the store via "index", "title", "group", "groupOrder" and "order" (see [here](https://github.com/wnielson/sencha-SlideNavigation/blob/master/ux/slidenavigation/View.js#L549)).

My suggestion is that you use the code snippet I posted before and filter based `record.get('title')`.  Hope that helps.
