### ISSUE TITLE
Ext.Viewport.setMasked({xtype: 'loadmask', message: 'Loading...'}); gives trouble

### ISSUE THREAD

**Issue by Tarang** [wnielson/sencha-SlideNavigation#28]
Sorry I keep creating issues, im not really a sencha pro but if you need help with node like stuff im ok with patching your stuff there

Im running:

``` javascript
Ext.Viewport.setMasked({xtype: 'loadmask', message: 'Loading...'});
```

But the mask comes on the menu instead of the viewport. I'm not too sure how to access the whole screen

**Comment by wnielson** [comment]
Thanks for catching this edge case.  Should be fixed now.
