### ISSUE TITLE
How to set an item as active programatically

### ISSUE THREAD

**Issue by Tarang** [wnielson/sencha-SlideNavigation#30]
I'm trying to use

``` javascript
Ext.getCmp('main').setActiveItem(1)
```

I call my slidenavigation main with an id, but this doesn't seem to work, is there a way to set the active item item on the menu. When coming back from a facebook login I'm trying to get it to go to where it was before

**Comment by wnielson** [comment]
Do the following:

```
Ext.getCmp('main').list.select(1)
```
