### ISSUE TITLE
Different colour slidenav

### ISSUE THREAD

**Issue by Tarang** [wnielson/sencha-SlideNavigation#33]
Is there a way to use a darker colour for the slidenav, like on the fastbook example at http://www.sencha.com/blog/the-making-of-fastbook-an-html5-love-story/

Is it as simple as setting cls? I could make up some css for a push request & example could you give me a bit of how to do this?

**Comment by wnielson** [comment]
Sure, it is possible.  You can target the `x-slidenavigation-list` class in CSS or use a custom 'ui' config option in the `list` config and then add some CSS in your sass style sheet.  Here's an example of how one user has modified the component:

![iOS Simulator Screen shot Mar 4 2013 9 52 56 AM](https://f.cloud.github.com/assets/32327/217730/afb66a04-84f4-11e2-982c-3addee239278.png)

**Comment by hessius** [comment]
I can't find any documentation on how to add custom ui classes to the list css variables / mixins (vs e.g. `@include sencha-toolbar-ui('darklist', darken($base-color, 45%), 'glossy');` )

And I can't get the targeting of the x-slidenavigation-list to work. Is this the wrong approach?

``` javascript
.x-slidenavigation-list {
$list-bg-color: darken($base-color, 15%);
$list-header-bg-color: darken($base-color, 45%);
}
```

**Comment by wnielson** [comment]
Yeah, the list styling in Sencha isn't as flexible as I think many would like.  Checkout this [example](https://github.com/wnielson/sencha-SlideViewExample/blob/master/resources/sass/app.scss) for an idea of one way to go about this.
