### ISSUE TITLE
Back button from navigationview shows before the slide button

### ISSUE THREAD

**Issue by ibudai** [wnielson/sencha-SlideNavigation#36]
When used in combination with a navigationview, the back button from the navigation bar shows first, before the slide button. I guess I would have expected the slide button to always show first. Is there some workaround for this?

**Comment by NeoMorfeo** [comment]
you could use the "docked" configuration on the button of the slide button ;), it works... but for me not perfect fit

**Comment by ibudai** [comment]
I have tried that myself too but it just doesn't look right. And during the animation, when changing cards it looks even worse.

**Comment by wnielson** [comment]
You have to get a little crafty in order to make the slide button work and look proper with a navigation view.  Here's an example of two listeners you can use to help achieve what you're looking to do:

``` javascript
back: function(nav) {
    if (nav.getInnerItems().length == 2) {
        bar = nav.getNavigationBar();
        bar.down('button[name="slidebutton"]').show({
            type: 'fade',
            out: false,
            duration: bar.getAnimation().duration
        });
    }
},
push: function(nav) {
    var bar = nav.getNavigationBar();
    bar.down('button[name="slidebutton"]').hide({
        type: 'fade',
        out: true,
        duration: bar.getAnimation().duration
    });
}
```

**Comment by ibudai** [comment]
Thanks, but this is not exactly what I wanted to achieve. I don't want to hide the slide button, I just wanted to position it before the back button. I thought maybe there was an easier solution that would just make it work. :)

**Comment by ibudai** [comment]
After giving it some more though, I think that using docked on the slide button is the easiest way to go. So additional config to the slide button:

``` javascript
docked: 'left',
margin: '.4em .2em .3em .2em',
```

And something similar for the back button in the navigation bar:

``` javascript
navigationBar: {
    backButton: {
        align: 'left',
        hidden: true,
        margin: '.4em .2em .3em .2em'
    }
}
```

Thanks guys for your help.
