### ISSUE TITLE
Second instance of the slidenavigation does not work

### ISSUE THREAD

**Issue by ibudai** [wnielson/sencha-SlideNavigation#37]
When using 2 instances for example, the second one is not being initialized correctly and therefore does not work (even after destroying the first instance).

**Comment by wnielson** [comment]
Yeah, this is a shortcoming of this component as it is really designed to be used as the immediate child of the Viewport..  The newer (and still alpha) [Slide View](https://github.com/wnielson/sencha-SlideView) attempts to fix this, among other improvements.

**Comment by ibudai** [comment]
Thanks for your answer, will give it a try.
