### ISSUE TITLE
MVC Pattern

### ISSUE THREAD

**Issue by lagear** [wnielson/sencha-SlideNavigation#5]
First the code is great.

Second, I started a project with SlideNavigation, and it work perfect, but the problem is that when I attached a controller (like MVC pattern) all the events doesn't fire, by sample this code dont fire when I active the selected view from the slide menu.

Ext.define('App.controller.ExtractoConsulta', {
    extend: 'Ext.app.Controller',

```
requires: [
'App.view.ExtractoConsulta',
],

config: {
    refs: {
        extractoConsultaView : '#extractoconsulta'
    },

    control: {
        extractoConsultaView: {
            activate: 'onExtractoConsultaActivate'
        }
    }
},

onExtractoConsultaActivate: function(sender , newActiveItem, oldActiveItem, eOpts)
{
    console.log('Activate event fired.');
}
```

});

**Comment by wnielson** [comment]
Thanks for the report.  I've been meaning to address some event issues for a while, so I'll take a look at this as well.

**Comment by lagear** [comment]
Thanks, I'm waiting for test

Best,

Marcos

2012/10/9 Weston notifications@github.com

**Comment by wnielson** [comment]
Events were added in version 0.2.0.
