### ISSUE TITLE
Build with Sencha Cmd v3.1.1

### ISSUE THREAD

**Issue by radroadsigns** [wnielson/sencha-SlideNavigation#50]
Thank you so much for this wonderful menu! I have it working in a Sencha Touch 2.2 app. I had to tweak things a bit to get containerSlideDelay and the vertical scroll lock to work.

When I try to build with Sencha Cmd, I get the error: "Failed to resolve dependency Ext.ux.slidenavigation.View for file MyApp.view.Main"

Based on the readme file, I presume this is due to not editing sencha.cfg properly. I can't find .sencha/app/sencha.cfg but have edited touch/cmd/sencha.cfg in my app directory. Maybe I'm not setting app.classpath properly. I have ux/slidenavigation/View.js in my app directory.

Any advice would be greatly appreciated.

**Comment by radroadsigns** [comment]
If anyone is interested, I solved my own problem and was able to build by adding a reference to the ux/slidenavigation directory in the framework.classpath line of the touch/cmd/sencha.cfg file.

**Comment by whatcould** [comment]
Worked for me too. I only had to change it when I upgraded to 2.2. To be more explicit, if you keep ux in /packages/ux, the line in `touch/cmd/sencha.cfg` is:

```
framework.classpath=${framework.dir}/src,packages/ux
```
