### ISSUE TITLE
Ext.ux namespace is confusing

### ISSUE THREAD

**Issue by dawesi** [wnielson/sencha-SlideNavigation#6]
Ext.ux is a reserved namespace for internal Sencha plugins. 

People get confused with who wrote the plugin if you namespace it this way.

**Comment by wnielson** [comment]
I changed this to Ext.ux after being told that using such a namespace was
the proper convention.  A quick search for 'Ext.ux' also returns many
user-contributed extensions.  Is there a preferred namespace then?

On Sep 5, 2012, at 3:08 PM, Chris Dawes notifications@github.com wrote:

Ext.ux is reserved for official Sencha extensions, please change this to
something else. It's not only bad practice, but confuses people to who
wrote the extension.

—
Reply to this email directly or view it on
GitHubhttps://github.com/wnielson/sencha-SlideNavigation/issues/6.

**Comment by Martin1982** [comment]
Maybe we should come up with such a convention. Not all Ext components are user experience components (like proxies), so it already is kind of strange to use it. Something like Ext.extension clarifies more that a component is third party.

Op 5 sep. 2012, om 15:08 heeft Chris Dawes notifications@github.com het volgende geschreven:

**Comment by wnielson** [comment]
How about `Ext.contrib.ux`?

**Comment by christocracy** [comment]
Ext.ux is commonly used for 3rd party extensions.

ux _means_ "User eXtension".

I've used Ext since 2006.

**Comment by wnielson** [comment]
Sounds good to me.  Thanks!
