### ISSUE TITLE
Slide navigation affects to the segmented button and this doesn´t work 

### ISSUE THREAD

**Issue by inane** [wnielson/sencha-SlideNavigation#74]
Hi!!

I am working with your plugin and I have the next issue, under W8 mobile device. 
![screenshot](https://cloud.githubusercontent.com/assets/1516015/6915453/78331362-d794-11e4-9ad6-3c3ad1c9e5c9.PNG)

I have the next layout and with the IE version mobile is impossible to do tap in the segmented-button, but if I change the navigation button to the right side of the segmented button works correctly, What am I doing wrong? this bug only appears under IE in a mobile device. I know it´s a tricky issue to explain but I expect you know what I mean.

Thanks in advance and sorry for my english.

**Comment by iosipeld** [comment]
Maybe it's a problem with CSS z-index. Try to tweak the css of your segmented buttons and give them a higher index.

**Comment by inane** [comment]
Thank you for your response, I solved this problem, moving the segmented-button to other position

Regards.
